### ISSUE TITLE
Mechanics Sketchup files cannot be opened

### ISSUE THREAD

**Issue by jonasdagefoerde** [MaslowCNC/Mechanics#29]
The Mechanics/Machine.skp and Mechanics/TempSeld.skp cannot be opened with Sketchup (latest version: 17.2.2554) on OSX (10.11.6)

**Comment by BarbourSmith** [comment]
This is a pretty common problem and I'm not sure what the solution is. I've heard from people that if you use the download button and download the zip file then they work, but if you download each file individually they don't.
![download](https://cloud.githubusercontent.com/assets/9359447/24760009/2a3e5b42-1a9c-11e7-93e5-a3c276153b73.JPG)

We need to find a better way so we stop confusing everyone, I'm not sure what the better way is.

**Comment by jonasdagefoerde** [comment]
Hi bar,

thanks for the tip: now it works :) May be you can add a hint to the README file for the time being - until you found a solution.


Cheers
Jonas

**Comment by BarbourSmith** [comment]
Great suggestion!
