### ISSUE TITLE
NOT an issue, just need to host image file of alternative frame design

### ISSUE THREAD

**Issue by aluminumwelder** [MaslowCNC/Mechanics#30]
this is NOT an issue, just need to host image file for new wiki page I made, couldn't figure out any other wayt to do this. 
![maslow frame](https://cloud.githubusercontent.com/assets/27420463/25006434/b6270062-2011-11e7-8288-aff280c43ccb.jpg)

**Comment by BarbourSmith** [comment]
They way I have been hosting pictures is to put them in the "documentation" folder on GitHub, there's a guide for how to do that: http://www.maslowcnc.com/howtocontribute/

But if you don't want to do that whole process I can put them in there for you.

**Comment by aluminumwelder** [comment]
ok sorry

**Comment by BarbourSmith** [comment]
Not to worry, good solution. I'm going to move the picture and I'll just update where the link points on the wiki page. Thank you for making a wiki page!

**Comment by BarbourSmith** [comment]
Great, I've added the photo to the repo. Awesome work!
