### ISSUE TITLE
Z-Axis Help

### ISSUE THREAD

**Issue by Seventhram** [MaslowCNC/Mechanics#47]
Can someone please tell me which port to plug the Z-Axis cable too.

Can someone please post a picture of the mounting of their Z-Axis.

Suggestions on the best way to remove the knob and dial on a Ridgid R2200 router.

**Comment by BarbourSmith** [comment]
Great questions, thanks for pointing that there needed to be a clear guide to that process. There is now a guide [here](https://github.com/MaslowCNC/Mechanics/wiki/How-To-Assemble-The-Z-Axis).

Let me know how I can make it better. 👍
