### ISSUE TITLE
Design braces to be shapes which can't be reversed

### ISSUE THREAD

**Issue by BarbourSmith** [MaslowCNC/Mechanics#49]
When assembling the legs it can be hard to tell which way the braces go. This could be fixed by making them more distinct shapes than triangles.

**Comment by mrfugu** [comment]
Similar to my response to Issue #32 , I'm happy to edit my Fusion360 file and export updated .svgs for Angle Braces 4 and 5.

**Comment by mrfugu** [comment]
Angle Braces 4 and 5 no longer exist. 
this issue can be closed.
