### ISSUE TITLE
Detailed specs for motors and encoders

### ISSUE THREAD

**Issue by rodrigogoncalves** [MaslowCNC/Mechanics#52]
Hi, is the [BOM](https://github.com/MaslowCNC/Mechanics/blob/master/BOM.txt) the official specs of the parts used? I'd like to know the makes and specs for the motors and encoders. Thanks

**Comment by davidelang** [comment]
the motors are custom built, they have a 291:1 worm gear with a 7-line encoder 
on the motor, resulting in 8148 pulses/rev of the output shaft, they have a 
final drive torque of 30Kg/cm and turn at 20 rpm

**Comment by Enjoying28** [comment]
I wonder if we can make a machine with these materials.

GM4632-370 DC 12V 30RPM High torque Turbo Encoder Motor Worm Geared Motor Reducer Motor
http://a.co/6l5dS2B
Browning 25B10 Minimum Bore Roller Chain Sprocket, Single Strand, Steel, 1/4" Stocked Bore, 10 Teeth
http://a.co/3dT9nYc
25 Roller Chain 50 Feet with 5 Connecting Links
http://a.co/0Qzel3k
Makeblock MegaPi - Born to Motion Control for Maker and Geek
http://a.co/iL2OnRn
Makeblock Megapi Encoder/DC Motor Driver 
http://a.co/3wgzsT6
NEWSTYLE 12v 30a Dc Universal Regulated Switching Power Supply 360w for CCTV, Radio, Computer Project
http://a.co/7Ea39eI

maybe would have to edit the step factor

**Comment by davidelang** [comment]
looks plausable, I'll point out that you are driving three motors which take 
<0.5A each, so your 30A power supply is drastic overkill

The motor's rated torque is less than the maslow motors, but the worst that will 
happen is that this means you have to go slower.

there will probably be some software changes needed to make the software run on 
that board (and it's not clear from the Amazon page how much flash is on that 
board, so double check that there is enough space.

David Lang

**Comment by mrfugu** [comment]
an optional/equivalent parts list has been created. 
this issue can be closed.
