### ISSUE TITLE
All_Parts_Laid_Out.svg AngleBrace1 error

### ISSUE THREAD

**Issue by mrfugu** [MaslowCNC/Mechanics#53]
In the file "All_Parts_Laid_Out.svg" the patterns (2) for the part called 'AngleBrace1.svg' has a sub-mm inconsistency in its long sides. 

This doesn't seem to exist in the "AngleBrace1.svg' file itself, just the "All_Parts_Laid_Out.svg" file. It's minor, but probably adds unnecessary complexity to the tool paths generated for this part using this consolidated file. 

-mrfugu

**Comment by mrfugu** [comment]
Correction: This error appears on the long 90 deg edge of the AngleBrace1 shape, which appears 4x in the " "All_Parts_Laid_Out.svg" file

**Comment by BarbourSmith** [comment]
Good catch! Thanks for noticing that. If you want to make a pull request which fixes it, I would love to merge it. If not I'll look into correcting the issue.

**Comment by mrfugu** [comment]
Cool, will do it now.

**Comment by mrfugu** [comment]
this is my 1st Github contribution, apologies if I made a mess of it.

**Comment by mrfugu** [comment]
Well, the file is in my post, but it reads to me like i requested a merge of recently changed files as well, not my intent.

**Comment by BarbourSmith** [comment]
😀 You ARE helping!

It seems like maybe a bunch of other files got wrapped up in the pull request for some reason, maybe give signing [the guest book](http://www.maslowcnc.com/howtocontribute) a go to test the process out

**Comment by mrfugu** [comment]
Hey, thanks! 

	Sorry about that, I’ll read more instructions before any future contributions, hope I didn’t make too big of a mess! 


	Cheers, 


Robert Crecine
429 1st Ave 
Suite 8
Pittsburgh, PA 15219
412-580-8618

**Comment by BarbourSmith** [comment]
The beautiful thing about Git Hub is it's virtually impossible to mess anything up. Every change is logged and reversible so you can pretty much always go for it! 👍 👍

**Comment by mrfugu** [comment]
Ok, I think I got it right this time, I re-submitted the corrected 'All_Parts_Laid_Out.svg' file.

**Comment by BarbourSmith** [comment]
Just merged it. Fantastic work! Thank you. 
👍 👍 👍
