### ISSUE TITLE
Why does the shop have a picture of z-axis mounted sideways on a motor mounting plate?

### ISSUE THREAD

**Issue by GeroBH** [MaslowCNC/Mechanics#84]
Just curious and confused.
http://www.maslowcnc.com/store/z-axis
Middle picture
[https://static1.squarespace.com/static/57e561e720099e0d7a7f6aca/58276a5bf7e0ab81d3e577ae/589a5e20bf629ac702e0b122/1486596219084/Sideways.jpg?format=750w](url)

**Comment by BarbourSmith** [comment]
In retrospect that is weird. Some routers have an adjustment knob on the side so the brackets are designed to work in both directions. As far as I know nobody has used that feature 🤷‍♂️
