### ISSUE TITLE
Broken link in wiki ("Z-Axis" page)

### ISSUE THREAD

**Issue by abetusk** [MaslowCNC/Mechanics#88]
There is a broken link to a picture at the bottom of the [Z-Axis](https://github.com/MaslowCNC/Mechanics/wiki/Z-Axis) wiki page.

There is a picture of attaching a bungee cord to the router to take care of the slop and give more consistent cuts.  The picture was, as far as I can tell, originally posted to [the forum](https://forums.maslowcnc.com/t/z-axis-bungee-to-ensure-correct-depth/481).  There was a request to add it to the wiki, which was done, but the picture that was linked to has since rotted.

In general, maybe there should be a policy of linking, as much as possible, to pictures internal to the repo to avoid this type of link rot?  Could we add an 'img' folder somewhere so that the wiki can use that to point to images it needs?

**Comment by BarbourSmith** [comment]
Great catch! 

I've uploaded the image to the folder here: https://github.com/MaslowCNC/Mechanics/tree/master/Documentation

so the link will not break again. I agree that we should try to keep all our meda internal. I guess that would require pull requests to be made for pictures, but I think it's worth it

**Comment by abetusk** [comment]
Thanks!
