### ISSUE TITLE
Broken link or missing info

### ISSUE THREAD

**Issue by Shady-Grove** [MaslowCNC/Mechanics#97]
https://github.com/MaslowCNC/Mechanics/wiki/0.25in-2-Flute,-Tungsten,-Up-Spiral-Bit

Instead of showing info on the 2 flute bit is returns me to home (parent menu).  Thanks!

**Comment by BarbourSmith** [comment]
Very strange, this link works for me https://github.com/MaslowCNC/Mechanics/wiki/0.25in-2-Flute,-Carbide,-Up-Spiral-Bit

On which page are you clicking the broken link?

**Comment by servant74** [comment]
Shady-Grove link uses the word Tungsten, where Bar's uses Carbide,

sounds like a little typeo onsome page.

**Comment by BarbourSmith** [comment]
@Shady-Grove What page was it on so we can fix it and close the issue?

**Comment by Shady-Grove** [comment]
When I click on this link:

https://github.com/MaslowCNC/Mechanics/wiki/0.25in-2-Flute,-Tungsten,-Up-Spiral-Bit

It takes me here:

https://github.com/MaslowCNC/Mechanics/wiki

Thanks.

**Comment by BarbourSmith** [comment]
Where are you seeing that link? The link takes you to a page which doesn't exist so you get bounced back to the front page of the wiki

**Comment by Shady-Grove** [comment]
Sorry, your email went to the junk file I just found it.  The top link here:

https://github.com/MaslowCNC/Mechanics/wiki/Tested-Router-Bits-Guide

(0.250in 2-Flute, Tungsten, Up Spiral Bit<https://github.com/MaslowCNC/Mechanics/wiki/0.25in-2-Flute,-Tungsten,-Up-Spiral-Bit>)
